numero1 = int()
numero2 = int()
numero3 = int()
print("Ingrese los numeros : ")
numero1 = int(input("ingrese el primer numero : "))
numero2 = int(input("ingrese el segundo numero : "))
numero3 = int(input("ingrese el tercer numero : "))
resultado = (numero1 + numero2 + numero3)
print("El resultado de la sumatoria es : ",resultado)
